// Generated by gencpp from file mynteye_wrapper_d_beta/Temp.msg
// DO NOT EDIT!


#ifndef MYNTEYE_WRAPPER_D_BETA_MESSAGE_TEMP_H
#define MYNTEYE_WRAPPER_D_BETA_MESSAGE_TEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mynteye_wrapper_d_beta
{
template <class ContainerAllocator>
struct Temp_
{
  typedef Temp_<ContainerAllocator> Type;

  Temp_()
    : header()
    , data(0.0)  {
    }
  Temp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> const> ConstPtr;

}; // struct Temp_

typedef ::mynteye_wrapper_d_beta::Temp_<std::allocator<void> > Temp;

typedef boost::shared_ptr< ::mynteye_wrapper_d_beta::Temp > TempPtr;
typedef boost::shared_ptr< ::mynteye_wrapper_d_beta::Temp const> TempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mynteye_wrapper_d_beta

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mynteye_wrapper_d_beta': ['/home/mynt/mynt/mynt-eye-d-sdk/wrappers/beta_ros/src/mynteye_wrapper_d_beta/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef848af8cf12f6df11682cc76fba477b";
  }

  static const char* value(const ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef848af8cf12f6dfULL;
  static const uint64_t static_value2 = 0x11682cc76fba477bULL;
};

template<class ContainerAllocator>
struct DataType< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mynteye_wrapper_d_beta/Temp";
  }

  static const char* value(const ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32 data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Temp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mynteye_wrapper_d_beta::Temp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYNTEYE_WRAPPER_D_BETA_MESSAGE_TEMP_H
